name: Update Pinned Gists
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  workflow_dispatch: 
  
jobs:
  update-gists:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - run: npm install
     - name: Update LeetCode Stats
       uses: ./
       env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: ${{ secrets.GIST_ID }}
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
     - name: Update ASCII Art Gist
       run: node art.js
       env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          ART_GIST_ID: ${{ secrets.ART_GIST_ID }}
